PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX outt_m: <http://swepub.kb.se/SwePubAnalysis/OutputTypes/model#>

CONSTRUCT {

 ?Record a mods_m:Record;
        swpa_m:publicationStatus ?_status;
        mods_m:identifierValue ?_recordID;
           swpa_m:publicationStatus ?_status;
           swpa_m:publicationYear ?_pubYear;
           mods_m:recordContentSourceValue ?_orgCode;
           swpa_m:publicationTypeCode ?_publicatType;
           swpa_m:contentTypeCode ?_contentType;
           swpa_m:oaType ?_OA;
           mods_m:hasSubject ?Subject ;
           foaf:name ?_name ;
           swpa_m:orcid ?_orcid ;
           outt_m:code ?_outputCode.

    ?Subject
        swpa_m:hsv1 ?_hsv1;
        swpa_m:hsv3 ?_hsv3;
        swpa_m:hsv5 ?_hsv5 .
   #?Name
   #  foaf:name ?_name .
   #?Orcidname
   #  swpa_m:orcid ?_orcid .




} WHERE {
    ?Record mods_m:hasMods ?Mods .
    ?Record a mods_m:Record .
    ?Mods a mods_m:Mods .
    ?Mods mods_m:identifierValue ?_recordID .
    ?Record swpa_m:publicationStatus ?_status .
    ?Mods swpa_m:publicationYear ?_pubYear .
    ?Mods mods_m:recordContentSourceValue ?_orgCode .
    ?Mods swpa_m:publicationTypeCode ?_publicatType .
    ?Mods swpa_m:contentTypeCode ?_contentType .

    FILTER ( xsd:string(?_orgCode) IN ( "${orgCodeArg}") )
    #FILTER ( xsd:string(?_recordID) IN ("oai:DiVA.org:sh-10626","oai:DiVA.org:sh-19653") )
    OPTIONAL { ?Mods swpa_m:oaType ?_OA }

  #OPTIONAL
  #{
  #  ?DataQualityViolation a swpa_m:DataQualityViolation .
  #  ?DataQualityViolation swpa_m:relatedRecord ?Record .
  #  ?DataQualityViolation a ?_violationType.
    #?_violationType rdfs:label ?_violationTypeLabel .
    #?_violationType swpa_m:severity ?_severity .
    #FILTER ( ?_violationType != swpa_m:DataQualityViolation )
   #}

  OPTIONAL
  {
        ?Record mods_m:hasMods ?Mods .
        ?Record a mods_m:Record .
        ?Mods a mods_m:Mods .
        ?Name a mods_m:Name .
        ?Record swpa_m:hasLocalCreator ?Name .
        ?Name foaf:name ?_name .
   }

    OPTIONAL
    {
        ?Record swpa_m:hasOutputType ?OutputType .
        ?OutputType outt_m:code ?_outputCode .
    }

    OPTIONAL
    {
            ?Record mods_m:hasMods ?Mods .
            ?Record a mods_m:Record .
            ?Mods a mods_m:Mods .
            ?Name a mods_m:Name .
            ?Record swpa_m:hasLocalCreator ?Name .
            #?Name foaf:name ?_name .
            ?Name swpa_m:orcid ?_orcid .
    }
   OPTIONAL
    {
        ?Mods mods_m:hasSubject ?Subject .
        ?Subject swpa_m:hsv1 ?_hsv1 .
    }

    OPTIONAL
    {
        ?Mods mods_m:hasSubject ?Subject .
        ?Subject swpa_m:hsv3 ?_hsv3 .
    }

    OPTIONAL
    {
        ?Mods mods_m:hasSubject ?Subject .
        ?Subject swpa_m:hsv5 ?_hsv5 .
    }

}

