# Max table Original data
PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#>
PREFIX outt_m: <http://swepub.kb.se/SwePubAnalysis/OutputTypes/model#>
PREFIX xlink: <http://www.w3.org/1999/xlink#> 
SELECT DISTINCT
?_recordID #Record ID
?_orgCode #Organisation (*)
?_pubYear #Publiceringsår
?_status #Publiceringsstatus #-
?_publicatType #Publikationstyp (*)
?_contentType #Innehållstyp #-
?_outputCode  #Vetenskaplig output
?_OA #OA typ (*) #-
?_hsv1 #Ämne nivå 1 (*) #-
?_hsv3 #Ämne nivå 2 (*) 
?_hsv5 #Ämne nivå 3 (*) #-
?_titleValue #Titel (*) #-
?_creatorCount #Totalt antal upphovspersoner
?_numLocalCreator #Totalt antal lokala upphovspersoner
?_name #Upphov (*) #-
?_localID #Lokalt person ID (*) #-
?_orcid #ORCID (*) #-
?_affiliation #Affiliering  (*) #-
?_channel #Värdpublikation (*) #-
?_issn #ISSN (*) #-
?_publisher #Förlag (*) #-
?_uri #Länk till arkiv (*) #-
?_fulltext #Fulltextlänk (*) #-
?_isiValue #ISI ID (*)
?_doiValue #DOI (*)
?_scopusValue #Scopus ID
?_pmidValue #Pubmed ID
?_isbnValue #ISBN (*) 
?_projekt #Projekt #-
?_program #Program #-
?_contract #Kontrakt #-
?_dubblettID # Dublett ID
WHERE
{
?Record a mods_m:Record .
?Mods a mods_m:Mods .

?Mods mods_m:identifierValue ?_recordID .

#START_<?_status>
?Record swpa_m:publicationStatus ?_status . 
#END_<?_status>

#START_<?_creatorCount>
OPTIONAL { ?Record swpa_m:creatorCount ?_creatorCount }
#END_<?_creatorCount>

#START_<?_numLocalCreator>
OPTIONAL { ?Record swpa_m:localCreatorCount ?_numLocalCreator . } 
#END_<?_numLocalCreator>

#START_<?_titleValue>

?Mods mods_m:hasTitleInfo ?TitleInfo .
MINUS { ?TitleInfo mods_m:type 'alternative'^^xsd:string }
?TitleInfo mods_m:hasTitle ?Title .
?Title mods_m:titleValue ?_titleValue .
#END_<?_titleValue>

#START_<?_uri>	
?Record swpa_m:uriRepository ?_uri .
#END_<?_uri>

#START_<?_fulltext>
OPTIONAL { ?Record swpa_m:uriFulltext ?_fulltext . }
#END_<?_fulltext>
#START_<?_outputCode>
OPTIONAL {
?Record swpa_m:hasOutputType ?OutputType .
?OutputType outt_m:code ?_outputCode .
}
#END_<?_outputCode>
#START_<?_doiValue>
OPTIONAL
{
?Mods mods_m:hasIdentifier ?DOI .
?DOI mods_m:doiValue ?_doiValue .
}
#END_<?_doiValue>


#START_<?_dubblettID>
OPTIONAL
{
?Record swpa_m:possiblySameAs ?Dubblett .
?Dubblett mods_m:hasMods ?Mods2 .
?Mods mods_m:identifierValue ?_dubblettID .
}
#END_<?_dubblettID>

#START_<?_isiValue>
OPTIONAL
{
?Mods mods_m:hasIdentifier ?ISI .
?ISI mods_m:isiValue ?_isiValue .
}
#END_<?_isiValue>

#START_<?_scopusValue>
OPTIONAL
{
?Mods mods_m:hasIdentifier ?Scopus .
?Scopus mods_m:scopusValue ?_scopusValue .
}
#END_<?_scopusValue>

#START_<?_pmidValue>
OPTIONAL
{
?Mods mods_m:hasIdentifier ?PMID .
?PMID mods_m:pmidValue ?_pmidValue .
}
#END_<?_pmidValue>

#START_<?_isbnValue>
OPTIONAL
{ 
?Mods mods_m:hasIdentifier ?ISBN .
?ISBN mods_m:isbnValue ?_isbnValue .
} 
#END_<?_isbnValue>

#START_<?_channel>
OPTIONAL { ?Mods swpa_m:titleValueRelatedItem ?_channel }
#END_<?_channel>
#START_<?_issn>
OPTIONAL { ?Mods swpa_m:issnRelatedItem ?_issn }
#END_<?_issn>

#START_<?_publisher>
OPTIONAL
{
?Mods mods_m:hasOriginInfo ?OriginInfo .
?OriginInfo mods_m:hasPublisher ?Publisher .
?Publisher mods_m:publisherValue ?_publisher .
}
#END_<?_publisher>

{
SELECT DISTINCT ?Record ?Mods ?_pubYear ?_orgCode ?_publicatType ?_contentType ?_hsv1 ?_hsv3 ?_hsv5 ?_OA ?_name ?_localID ?_orcid ?_affiliation
WHERE
{
?Record mods_m:hasMods ?Mods .
?Record a mods_m:Record .
?Mods a mods_m:Mods .

?Mods swpa_m:publicationYear ?_pubYear .
?Mods mods_m:recordContentSourceValue ?_orgCode .

?Mods swpa_m:publicationTypeCode ?_publicatType .
?Mods swpa_m:contentTypeCode ?_contentType .
?Record swpa_m:isPublished ?_isPublished .
?Mods mods_m:hasName ?Name .
OPTIONAL { ?Mods swpa_m:oaType ?_OA }

#START_<?_hsv1>
OPTIONAL
{ 
?Mods mods_m:hasSubject ?Subject .
?Subject swpa_m:hsv1 ?_hsv1 .
}
#END_<?_hsv1>

#START_<?_hsv3>
OPTIONAL
{ 
?Mods mods_m:hasSubject ?Subject .
?Subject swpa_m:hsv3 ?_hsv3 .
}
#END_<?_hsv3>


#START_<?_hsv5>
OPTIONAL
{ 
?Mods mods_m:hasSubject ?Subject .
?Subject swpa_m:hsv5 ?_hsv5 .
}
#END_<?_hsv5>


#START_<?_name>

?Name foaf:name ?_name .
#END_<?_name>
#START_<?_localID>
OPTIONAL{ ?Name xlink:href ?_localID }
#END_<?_localID>
#START_<?_orcid>
OPTIONAL{ ?Name swpa_m:orcid ?_orcid }
#END_<?_orcid>
#START_<?_affiliation>
OPTIONAL
{
?Name mods_m:hasAffiliation ?Affiliation .
?Affiliation mods_m:authority 'kb.se'^^xsd:string .
?Affiliation mods_m:valueURI ?_affiliation .
}
#END_<?_affiliation>
###  FILTERS START ####
#START_<ONE_CREATOR_NAME_FILTER>
?Mods mods_m:hasName ?Name .
?Name foaf:name ?_name .
#FILTER_<?_name> ( bif:contains(?_name, <?_name> ) )
OPTIONAL { ?Name swpa_m:orcid ?_orcid }
#END_<ONE_CREATOR_NAME_FILTER>

#START_<ONE_CREATOR_ORCID_FILTER>
?Mods mods_m:hasName ?Name .
?Name foaf:name ?_name .
?Name swpa_m:orcid ?_orcid .
#FILTER_<?_orcid> ( xsd:string(?_orcid) = <?_orcid> )
#END_<ONE_CREATOR_ORCID_FILTER>

#START_<ONE_CREATOR_TWO_FILTERS>
{
?Mods mods_m:hasName ?Name .
?Name foaf:name ?_name .
OPTIONAL { ?Name swpa_m:orcid ?_orcid }
#FILTER_<?_name> ( bif:contains(?_name, <?_name> ) )
}
UNION
{
?Mods mods_m:hasName ?Name .
?Name foaf:name ?_name .
?Name swpa_m:orcid ?_orcid .
#FILTER_<?_orcid> ( xsd:string(?_orcid) = <?_orcid> )
}
#END_<ONE_CREATOR_TWO_FILTERS>
###  FILTERS START ####
#FILTER_<?_orgCode> ( xsd:string(?_orgCode) IN ( <?_orgCode> ) ) 
#FILTER_<?_pubYear_low> ( ?_pubYear >= <?_pubYear_low> ) 
#FILTER_<?_pubYear_high> ( ?_pubYear <= <?_pubYear_high> ) 
#FILTER_<?_publicatType> (xsd:string(?_publicatType) IN ( <?_publicatType> ) ) 
#FILTER_<?_contentType> (xsd:string(?_contentType) IN ( <?_contentType> ) ) 
#FILTER_<?_isPublished> ( ?_isPublished = <?_isPublished> ) 
#FILTER_<?_hsv3> ( xsd:int(?_hsv3) IN ( <?_hsv3> ) )
#FILTER_<?_OA> ( BOUND(?_OA ))
###  FILTERS END ####
}
LIMIT 500
}
}
LIMIT 100